lavalink:
  plugins:
    - dependency: com.github.topi314.lavasearch:lavasearch-plugin:1.0.0
      snapshot: false
    - dependency: com.github.topi314.lavasrc:lavasrc-plugin:4.8.3
      snapshot: false
    - dependency: com.github.topi314.sponsorblock:sponsorblock-plugin:3.0.1
      snapshot: false
  pluginsDir: ./plugins
  server:
    bufferDurationMs: 400
    filters:
      channelMix: true
      distortion: true
      equalizer: true
      karaoke: true
      lowPass: true
      rotation: true
      timescale: true
      tremolo: true
      vibrato: true
      volume: true
    frameBufferDurationMs: 5000
    gc-warnings: true
    nonAllocatingFrameBuffer: false
    opusEncodingQuality: 10
    password: "SowardLavalink2025"
    playerUpdateInterval: 5
    resamplingQuality: HIGH
    soundcloudSearchEnabled: true
    sources:
      bandcamp: false
      http: true
      local: false
      mixer: false
      nico: false
      soundcloud: true
      twitch: false
      vimeo: false
      youtube: false
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    youtubePlaylistLoadLimit: 0
    youtubeSearchEnabled: false
logging:
  file:
    max-history: 2
    max-size: 5MB
    path: ./logs/
  level:
    lavalink: INFO
    root: INFO
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 5
  request:
    enabled: false
    includeClientInfo: false
    includeHeaders: false
    includePayload: false
    includeQueryString: true
    maxPayloadLength: 10000
metrics:
  prometheus:
    enabled: false
    endpoint: /metrics
plugins:
  lavasrc:
    applemusic:
      albumLoadLimit: 3
      countryCode: IN
      playlistLoadLimit: 3
    flowerytts:
      audioFormat: flac
      silence: 500
      speed: 1
      translate: false
      voice: Anushri
    lyrics-sources:
      deezer: false
      spotify: false
      vkmusic: false
      yandexmusic: false
      youtube: false
    providers:
      - "amsearch:%QUERY%"
      - "scsearch:%QUERY%"
    sources:
      applemusic: true
      deezer: false
      flowerytts: true
      qobuz: false
      spotify: false
      tidal: false
      vkmusic: false
      yandexmusic: false
      youtube: false
    spotify:
      albumLoadLimit: 0
      countryCode: IN
      localFiles: false
      playlistLoadLimit: 0
      resolveArtistsInSearch: false
sentry:
  dsn: ""
  environment: ""
server:
  address: 0.0.0.0
  http2:
    enabled: false
  port: 2333
