services:
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:latest
    container_name: lavalink
    restart: unless-stopped
    cpus: 1.5
    mem_limit: 896m
    user: "322:322"
    environment:
      - _JAVA_OPTIONS=-Xms128M -Xmx768M
      - SERVER_PORT=2333
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml
      - ./plugins/:/opt/Lavalink/plugins/
    networks:
      - lavalink
    expose:
      - 2333
    ports:
      - "2333:2333"
    
networks:
  lavalink:
    name: lavalink
